### ISSUE TITLE
Orders sync does not work for multistore setup

### ISSUE THREAD

**Issue by yrudiuk** [YotpoLtd/magento2-module-yotpo-reviews#160]
**Preconditions**

- Magento 2.3.1
- Yotpo 2.7.7

**Issue**
Next error logged for every cron run of every store - "Please make sure you insert your APP KEY and SECRET and save configuration before trying to export past orders"
Orders sync does not work if Yotpo configuration set on website/store level. Process tries to load default configuration instead.

**Comment by DanGlz** [comment]
Hey @yrudiuk ,
Thanks for raising this.
Version 2.8.0 is available, upgrade your Yotpo module and let us know if the problem still exists.

Thanks.

**Comment by yrudiuk** [comment]
Hello,

It seems like it fixes our issue, however 2.8.0 breaks code build process.
We are using snapshot building without connection to database. And when process runs setup:di:compile, next error appears:
In ResourceConnection.php line 149:
Connection "default" is not defined

This is not happening on 2.7.7

**Comment by yrudiuk** [comment]
This caused specifically by the vendor/yotpo/module-review/Console/CommandList.php which uses object manager

**Comment by DanGlz** [comment]
Hey @yrudiuk ,

We just released v2.8.1 that suppose to fix the DB connection error.
Please upgrade to version v2.8.1 and let us know if you have any problems.

Thanks.

**Comment by yrudiuk** [comment]
Thank you. All good now

**Comment by yrudiuk** [comment]
However, orders still not sending and we are getting next info in debug log for every store:
Jobs::ordersSync() - Skipping store ID: 2 (disabled)" {"store_id":"1","app_key":null}

It seems like $this->_yotpoHelper->isEnabled() checks default config only?

**Comment by DanGlz** [comment]
It seems like  under sore id 2 yotpo disabled and your app key is empty.
Make sure to fill your App Key, API secret and to set **Enable Yotpo** --> yes for each store view.

![Screen Shot 2019-06-21 at 9 48 57](https://user-images.githubusercontent.com/25307324/59903528-e474ff00-9409-11e9-8d1c-65992e3542a3.png)

**Comment by yrudiuk** [comment]
@DanGlz thank you. This is working for us now.
